collections:
  dinoair_files:
    description: File embeddings for DinoAir3 search
    distance: Cosine
    name: dinoair_files
    vector_size: 384
  dinoair_notes:
    description: Note embeddings for semantic search
    distance: Cosine
    name: dinoair_notes
    vector_size: 384
  dinoair_projects:
    description: Project embeddings for discovery
    distance: Cosine
    name: dinoair_projects
    vector_size: 384
development:
  debug: false
  profiling: false
  reload: false
embeddings:
  batch_size: 32
  cache_dir: ~/.dinoair/models/embeddings
  cache_size: 1000
  max_length: 256
  model: all-MiniLM-L6-v2
integration:
  auto_sync: true
  batch_size: 100
  max_workers: 4
  sync_existing_data: true
  sync_interval_minutes: 30
logging:
  backup_count: 5
  file: logs/qdrant_mcp.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  level: INFO
  max_size: 10 MB
mcp:
  host: localhost
  log_level: INFO
  name: qdrant-mcp-server
  port: 8080
  version: 1.0.0
production:
  keep_alive: 75
  max_requests: 1000
  timeout: 30
  workers: 4
qdrant:
  api_key: ${QDRANT_API_KEY} # Resolved from environment at runtime; do not hardcode secrets
  grpc_port: 6334
  timeout: 30
  url: http://localhost:6333
search:
  default_limit: 10
  default_threshold: 0.7
  keyword_weight: 0.3
  max_limit: 50
  vector_weight: 0.7
security:
  cors:
    allowed_headers:
      - Content-Type
      - Authorization
      - X-Request-ID
    allowed_methods:
      - GET
      - POST
      - OPTIONS
    allowed_origins:
      - http://localhost:3000
      - http://127.0.0.1:3000
  rate_limit:
    burst_limit: 10
    requests_per_minute: 60
  validate_api_key: true
