version = 1

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "21"
  language_version = "2.1"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "21"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "cxx"

[[transformers]]
name = "ktlint"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "ruff"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "isort"