name: crypto_dash
description: "DinoAir Crypto Dashboard - A Flutter demonstration of clean architecture, Riverpod state management, and multi-source market data integration."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^14.6.2

  # HTTP client
  dio: ^5.7.0
  connectivity_plus: ^5.0.2
  pretty_dio_logger: ^1.3.1

  # Environment variables
  flutter_dotenv: ^5.2.1

  # Local storage
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Error tracking
  sentry_flutter: ^8.11.0

  # Charts
  fl_chart: ^0.70.1

  # Internationalization
  intl: ^0.20.1

  # Functional programming
  dartz: ^0.10.1

  # Code generation for immutable models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # URL launcher for opening files
  url_launcher: ^6.3.1

  # File picker for directory selection
  file_picker: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1

  # Testing and mocking
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - .env
