# ========================================================================
# DEPRECATED - Consolidated into .github/workflows/ci.yml
# ========================================================================
# This workflow has been merged into the main CI pipeline for better
# organization and to avoid job duplication.
# 
# SonarCloud analysis is now executed as the 'sonarcloud' job in ci.yml.
# See: .github/workflows/ci.yml
#
# REQUIRED SECRETS TO CONFIGURE:
# - SONAR_TOKEN: Your SonarCloud authentication token
# - GITHUB_TOKEN: (automatically provided)
#
# ORGANIZATION: dino-pit-studios-llc
# PROJECT KEY: Dino-pit-studios-llc_DinoAir3
# ======================================================================== 

name: DEPRECATED - Use ci.yml instead
on:
  push:
    branches:
      - __disabled__
jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated. Use .github/workflows/ci.yml"